### ISSUE TITLE
Size of images

### ISSUE THREAD

**Issue by SashaMalysheva** [avgaydashenko/Race#14]
Resize images, depending on the phone model

**Comment by SashaMalysheva** [comment]
Display display = ((WindowManager) getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay();

int width = display.getWidth(); 
int height = display.getHeight();

Изменение ширины

http://habrahabr.ru/sandbox/42926/

---

В итоге не сработало

**Comment by SashaMalysheva** [comment]
http://stackoverflow.com/questions/9230062/android-how-to-get-imageview-to-fill-screen

**Comment by avgaydashenko** [comment]
Done!
