### ISSUE TITLE
Remove frames around buttons

### ISSUE THREAD

**Issue by avgaydashenko** [avgaydashenko/Race#16]
Not this:

![default](https://cloud.githubusercontent.com/assets/11502139/10335227/062581e8-6cf8-11e5-9d26-468d3d5eaa0a.PNG)

But this:

![default](https://cloud.githubusercontent.com/assets/11502139/10335256/2e17bd6a-6cf8-11e5-9e09-d32ec01648f7.PNG)

**Comment by SashaMalysheva** [comment]
http://stackoverflow.com/questions/5457138/how-to-remove-imagebuttons-standard-background-image

**Comment by avgaydashenko** [comment]
Done.
