### ISSUE TITLE
Write "OnCLick" for buttonBack

### ISSUE THREAD

**Issue by avgaydashenko** [avgaydashenko/Race#17]
ButtonBack should work as button Back on your phone, not just go in parent-activity.

**Comment by nkly** [comment]
What question should I answer?

**Comment by avgaydashenko** [comment]
How create a buttonBack, which described above?

**Comment by nkly** [comment]
Call https://developer.android.com/reference/android/app/Activity.html#onBackPressed() inside button's onClick listener.
