### ISSUE TITLE
Write "OnCLick" for buttonSound

### ISSUE THREAD

**Issue by avgaydashenko** [avgaydashenko/Race#18]

**Comment by avgaydashenko** [comment]
Also to make sense to this issue, we need to create and realise some music in the game. And, maybe, some sound kinda "crash".

**Comment by avgaydashenko** [comment]
http://developer.alexanderklimov.ru/android/whosaidmeow.php

**Comment by nkly** [comment]
What question should I answer?

**Comment by SashaMalysheva** [comment]
http://geektimes.ru/post/232885/

**Comment by SashaMalysheva** [comment]
http://developer.alexanderklimov.ru/android/whosaidmeow.php

**Comment by SashaMalysheva** [comment]
http://www.findsounds.com/ISAPI/search.dll
Выбрать звуки:
смерть
начало игры
перманентный звук.

**Comment by SashaMalysheva** [comment]
https://www.youtube.com/watch?v=V1ocJmXeQ28
