### ISSUE TITLE
Learn how to change object

### ISSUE THREAD

**Issue by avgaydashenko** [avgaydashenko/Race#19]
You need to change this one:
![sound](https://cloud.githubusercontent.com/assets/11502139/10335333/95e9601a-6cf8-11e5-92c2-a1393a154eda.png)
to this:
![no_sound](https://cloud.githubusercontent.com/assets/11502139/10335337/9bd4a80e-6cf8-11e5-9b60-ccab0503e554.png)
after click.

**Comment by nkly** [comment]
Use http://developer.android.com/reference/android/widget/ImageView.html#setImageDrawable(android.graphics.drawable.Drawable) in `onClickListener`
