### ISSUE TITLE
Make no TitleBar theme

### ISSUE THREAD

**Issue by avgaydashenko** [avgaydashenko/Race#28]

**Comment by SashaMalysheva** [comment]
http://stackoverflow.com/questions/2591036/how-to-hide-the-title-bar-for-an-activity-in-xml-with-existing-custom-theme

**Comment by avgaydashenko** [comment]
Не работает.

**Comment by nkly** [comment]
https://developer.android.com/training/system-ui/immersive.html

**Comment by avgaydashenko** [comment]
I don't understand where I should write this code:

private void hideSystemUI() {
    mDecorView.setSystemUiVisibility(
            View.SYSTEM_UI_FLAG_LAYOUT_STABLE
            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION // hide nav bar
            | View.SYSTEM_UI_FLAG_FULLSCREEN // hide status bar
            | View.SYSTEM_UI_FLAG_IMMERSIVE);
}

**Comment by nkly** [comment]
This is just a snippet. You should adapt it to your needs. I think that the most important part is to be aware about `setSystemUiVisibility` and use it on your activity's `contentView`
