### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by SashaMalysheva** [avgaydashenko/Race#3]
Write the rules of the game one player and two players.

**Comment by SashaMalysheva** [comment]
Еще примеры настроек:
![Uploading 4I4UGNo_iRE.jpg…]()
![gat9wsccbga](https://cloud.githubusercontent.com/assets/11505069/10365745/3a99de8e-6dce-11e5-92c2-2bf452437e95.jpg)
![kuvlgm7o_1c](https://cloud.githubusercontent.com/assets/11505069/10365748/3a9c51d2-6dce-11e5-9ace-637d63dd1628.jpg)
![o_awjf0yu8u](https://cloud.githubusercontent.com/assets/11505069/10365746/3a9a1da4-6dce-11e5-9d89-b9eb21a4b083.jpg)
![Uploading RZWZJz8i2Sk.jpg…]()

**Comment by avgaydashenko** [comment]
Again same task with the issue #3
