### ISSUE TITLE
Messages client-server

### ISSUE THREAD

**Issue by SashaMalysheva** [avgaydashenko/Race#36]

**Comment by avgaydashenko** [comment]
> Еще был вопрос, какие сообщения мы хотим передавать по BlueTooth и получать, соответственно. Нам надо для парной игры знать, что делает второй игрок. То есть, когда пользователь наклоняет телефон, чтобы передвинуть фигурку, мы передаем это в класс, который отрисует картинку на другом месте, эти же данные передаем по BT, и другой телефон тоже должен изменить положение фигурки на экране.
