### ISSUE TITLE
Write a layout for the game

### ISSUE THREAD

**Issue by SashaMalysheva** [avgaydashenko/Race#9]
Write a game for one player

**Comment by SashaMalysheva** [comment]
[GameForOnePlayer.docx](https://github.com/avgaydashenko/Race/files/9267/GameForOnePlayer.docx)

**Comment by avgaydashenko** [comment]
http://pastebin.com/2pHypwRf

**Comment by avgaydashenko** [comment]
http://pastebin.com/ypQhjZHQ
Constants were added.
